/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-26 03:46:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CreateAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Register Page</title>\r\n");
      out.write(" <meta charset=\"UTF-8\">\r\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write(" <script>\r\n");
      out.write("    function validate() {\r\n");
      out.write("    	<!--Check if required fields are empty-->\r\n");
      out.write("    	var fname = document.getElementById(\"Fname\");\r\n");
      out.write("    	var lname = document.getElementById(\"Lname\");\r\n");
      out.write("    	var email = document.getElementById(\"email\");\r\n");
      out.write("    	var address = document.getElementById(\"address\");\r\n");
      out.write("    	var phone = document.getElementById(\"phone\");\r\n");
      out.write("    	var username = document.getElementById(\"username\");\r\n");
      out.write("    	var password = document.getElementById(\"password\");\r\n");
      out.write("        var confirmPassword= document.getElementById(\"repass\");\r\n");
      out.write("\r\n");
      out.write("        <!--Check if passwords match-->\r\n");
      out.write("        if(fname.value == \"\" || lname.value == \"\" || email.value.trim() == \"\" || address.value.trim() == \"\" ||\r\n");
      out.write("          phone.value.trim() == \"\" || username.value.trim() == \"\" || password.value.trim() == \"\" || confirmPassword.value.trim() == \"\"){\r\n");
      out.write("        	alert(\"Please fill all the fields accordingly\")\r\n");
      out.write("        	highlightEmptyFields();\r\n");
      out.write("        	return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        if (password.value !== confirmPassword.value) {\r\n");
      out.write("            alert(\"Passwords do not match.\");\r\n");
      out.write("            document.getElementById(\"password\").style.border = \"solid 2px red\";\r\n");
      out.write("            document.getElementById(\"repass\").style.border = \"solid 2px red\";\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        var emailPattern = /^[a-zA-Z0-9._%+-]+@gmail\\.com$/;\r\n");
      out.write("        if (!emailPattern.test(email.value.trim())) {\r\n");
      out.write("            alert(\"Please enter a valid Gmail address.\");\r\n");
      out.write("            email.style.border = \"solid 2px red\";\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            email.style.border = \"\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        var phonePattern = /^\\d{10}$/;\r\n");
      out.write("        if (!phonePattern.test(phone.value.trim())) {\r\n");
      out.write("            alert(\"Please enter a valid 10-digit contact number.\");\r\n");
      out.write("            phone.style.border = \"solid 2px red\";\r\n");
      out.write("            return false;\r\n");
      out.write("        } else {\r\n");
      out.write("            phone.style.border = \"\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          return true; \r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    function highlightEmptyFields() {\r\n");
      out.write("        var inputs = document.querySelectorAll('input[type=\"text\"], input[type=\"password\"]');\r\n");
      out.write("        inputs.forEach(function(input) {\r\n");
      out.write("            if (input.value === \"\") {\r\n");
      out.write("                input.style.border = \"solid 2.2px red\";\r\n");
      out.write("            } else {\r\n");
      out.write("                input.style.borderColor = \"\";\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write(" <style>\r\n");
      out.write("    \r\n");
      out.write("  body{\r\n");
      out.write("	         display:flex;\r\n");
      out.write("	         justify-content:center;\r\n");
      out.write("	         min-height:100vh;\r\n");
      out.write("	         background-image: linear-gradient(to bottom, #EBF9FB , #E9E0F5);\r\n");
      out.write("	}\r\n");
      out.write("  .wrapper{\r\n");
      out.write("	        zoom:0.9;\r\n");
      out.write("	        font-family: \"Lora\", serif;\r\n");
      out.write("	        margin-top:45px;\r\n");
      out.write("	        padding:5px;\r\n");
      out.write("		    width:899px;\r\n");
      out.write("			height:700px;\r\n");
      out.write("		    background:rgba(255, 255, 255, 0.9);\r\n");
      out.write("		    color:black;\r\n");
      out.write("			border: 3px solid #EEF7FC; \r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            box-shadow:rgba(0, 0, 0, 0.14) 0px 4px 11px;\r\n");
      out.write("            justify-content:space-between;\r\n");
      out.write("	} \r\n");
      out.write("  .container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("			margin:0;\r\n");
      out.write("        }\r\n");
      out.write("  .left-side {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("			display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding:0px;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            z-index: 0; \r\n");
      out.write("        }\r\n");
      out.write("  .signup-form {\r\n");
      out.write("			zoom: 0.83;\r\n");
      out.write("            width: 460px;\r\n");
      out.write("			height: 700px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("			position: relative; \r\n");
      out.write("            z-index: 1; \r\n");
      out.write("        }\r\n");
      out.write("  h1 {\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("			margin-top:0;\r\n");
      out.write("        }\r\n");
      out.write(" 	\r\n");
      out.write(" .signin-link {\r\n");
      out.write("            color: #B7ADEB;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("			font-weight:549.5;\r\n");
      out.write("			font-size:23px;\r\n");
      out.write("        }\r\n");
      out.write(" .signin-link:hover{\r\n");
      out.write("		    color:#9b5fad;\r\n");
      out.write("		}\r\n");
      out.write(" /*.signin-link a :hover{\r\n");
      out.write("		    color:#AD73BF;\r\n");
      out.write(" }*/\r\n");
      out.write("  .input-container {\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("  input[type=\"text\"], input[type=\"password\"] {\r\n");
      out.write("            width: 80%;\r\n");
      out.write("			font-family: \"Lora\", serif;\r\n");
      out.write("			font-size:19px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("			margin: 10px;\r\n");
      out.write("            border: 2px solid #ccc;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("  .button {\r\n");
      out.write("            width: 65%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("			margin:20px;\r\n");
      out.write("            background-color:#A677A5;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border:none ;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("			font-size:19px;\r\n");
      out.write("			font-family: \"Lora\", serif;\r\n");
      out.write("        }\r\n");
      out.write("  .button:hover{\r\n");
      out.write("            background-color:#55C4DD;\r\n");
      out.write("			}\r\n");
      out.write("  .right-side {\r\n");
      out.write("			z-index: 9;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            background-image: url('image/bg_n_s-removebg.png');\r\n");
      out.write("			background-size: 92% auto;\r\n");
      out.write("			background-repeat: no-repeat;\r\n");
      out.write("			background-position: 70% 35%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("  .gradient-overlay {\r\n");
      out.write("			z-index : 1;\r\n");
      out.write("			zoom: 0.9;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width:100%; \r\n");
      out.write("			/*\r\n");
      out.write("            background: linear-gradient(to right, rgba(255,255,250,0.5) 0%, rgba(255,255,250,0.6) 100%);\r\n");
      out.write("			*/\r\n");
      out.write("        }\r\n");
      out.write("  .logo {\r\n");
      out.write("            width: 340px; \r\n");
      out.write("            height: 100px; \r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 67%;\r\n");
      out.write("            left: 35%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            padding: 6px; \r\n");
      out.write("			z-index: 2; \r\n");
      out.write("        }\r\n");
      out.write("		\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write(" <div class=\"left-side\">\r\n");
      out.write("	<div class=\"signup-form\" align =\"center\">\r\n");
      out.write("        <h1>Sign up</h1>\r\n");
      out.write("        <form onsubmit=\"return validate()\" action=\"insert\" method=\"post\">\r\n");
      out.write("		    <input type=\"text\" id =\"Fname\" name=\"Fname\" placeholder=\"First name\">\r\n");
      out.write("            <input type=\"text\" id=\"Lname\" name=\"Lname\" placeholder=\"Last name\">\r\n");
      out.write("			<input type=\"text\" id=\"email\" name=\"email\" placeholder=\"Email\">\r\n");
      out.write("			<input type=\"text\" id=\"address\" name=\"address\" placeholder=\"Address\">\r\n");
      out.write("			<input type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"Contact\">\r\n");
      out.write("			<input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Username\">\r\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Password\">\r\n");
      out.write("			<input type=\"password\" id=\"repass\" name=\"repass\" placeholder=\"Confirm Password\">\r\n");
      out.write("            <input type=\"submit\" class=\"button\" name=\"submit\" value=\"Create Account\">\r\n");
      out.write("			<div class=\"sign-in\">\r\n");
      out.write("			<p style=\"font-size:19.9px;\">Already have an account? <a href=\"Login.jsp\" class=\"signin-link\">Sign in</a></p>\r\n");
      out.write("			</div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div class=\"right-side\">\r\n");
      out.write("	 <div class=\"gradient-overlay\"></div>\r\n");
      out.write("     <img class=\"logo\" src=\"image/logo.jpg\" alt=\"Logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("  </body>\r\n");
      out.write(" </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
